export enum GameState {
  SETUP = 'SETUP',
  LOBBY = 'LOBBY',
  TRACK_SELECTION = 'TRACK_SELECTION',
  PLAYING = 'PLAYING',
  ROUND_COMPLETED = 'ROUND_COMPLETED',
  RESULTS = 'RESULTS',
  GAME_FINISHED = 'GAME_FINISHED'
}

export enum Joker {
  OBFUSCATION = 'OBFUSCATION',
  TAGS = 'TAGS',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE'
}

export const MAX_VOLUME = 0.25;
export const DEFAULT_VOLUME_SLIDER_VAL = 0.5;
export const POLLING_INTERVAL = 500;