export const GameState = {
  LOBBY: 'LOBBY',
  TRACK_SELECTION: 'TRACK_SELECTION',
  PLAYING: 'PLAYING',
  ROUND_COMPLETED: 'ROUND_COMPLETED',
  RESULTS: 'RESULTS',
  GAME_FINISHED: 'GAME_FINISHED'
};

export const MAX_VOLUME = 0.25;
export const DEFAULT_VOLUME_SLIDER_VAL = 0.5;