export enum GameState {
  SETUP = 'SETUP',
  LOBBY = 'LOBBY',
  TRACK_SELECTION = 'TRACK_SELECTION',
  PLAYING = 'PLAYING',
  ROUND_COMPLETED = 'ROUND_COMPLETED',
  RESULTS = 'RESULTS',
  GAME_FINISHED = 'GAME_FINISHED'
}

export enum Joker {
  OBFUSCATION = 'OBFUSCATION',
  TRIVIA = 'TRIVIA',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE'
}

export const DEFAULT_TRACK_DURATION = 30000;
export const DEFAULT_ROUNDS = 5;
export const BASE_POINTS = 100;
export const FIRST_BONUS_MULTIPLIER = 1.2;