export enum GameState {
  LOBBY = 'LOBBY',
  TRACK_SELECTION = 'TRACK_SELECTION',
  PLAYING = 'PLAYING',
  ROUND_COMPLETED = 'ROUND_COMPLETED',
  RESULTS = 'RESULTS',
  GAME_FINISHED = 'GAME_FINISHED'
}