export enum GameState {
  SETUP = 'SETUP',
  LOBBY = 'LOBBY',
  TRACK_SELECTION = 'TRACK_SELECTION',
  PLAYING = 'PLAYING',
  ROUND_COMPLETED = 'ROUND_COMPLETED',
  RESULTS = 'RESULTS',
  GAME_FINISHED = 'GAME_FINISHED'
}

export enum Joker {
  OBFUSCATION = 'OBFUSCATION',
  TRIVIA = 'TRIVIA',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  SPY = 'SPY'
}

export const MAX_VOLUME = 0.25;
export const DEFAULT_VOLUME_SLIDER_VAL = 0.5;
export const POLLING_INTERVAL = 500;
export const DEFAULT_TRACK_DURATION = 60000;
export const DEFAULT_ROUNDS = 5;
export const BASE_POINTS = 100;
export const FIRST_BONUS_MULTIPLIER = 1.2;